[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    DB                /tmp/fluent-bit-tail.db
    Mem_Buf_Limit     32MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        correlation_id
    Reserve_Data  On
    Preserve_Key  On

[FILTER]
    Name          modify
    Match         docker.*
    Add           platform mytelco
    Add           environment local

[OUTPUT]
    Name                es
    Match               docker.*
    Host                opensearch
    Port                9200
    Logstash_Format     On
    Logstash_Prefix     mytelco-logs
    Replace_Dots        On
    Retry_Limit         False
    Suppress_Type_Name  On
