apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-customer-bff
  labels:
    app: customer-bff
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customer-bff
  template:
    metadata:
      labels:
        app: customer-bff
    spec:
      containers:
      - name: customer-bff
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
